create table expense_categories
(
    id   bigint generated by default as identity
        constraint expense_categories_pkey
            primary key,
    name varchar(255) not null
        constraint uk_k1sge706gm79khcwo1sfpmbgg
            unique
);

alter table expense_categories
    owner to postgres;

create table income_categories
(
    id   bigint generated by default as identity
        constraint income_categories_pkey
            primary key,
    name varchar(255) not null
        constraint uk_jlu96droogitln62024ljs3nt
            unique
);

alter table income_categories
    owner to postgres;

create table users
(
    id   bigint generated by default as identity
        constraint users_pkey
            primary key,
    name varchar(255) not null
        constraint uk_sx468g52bpetvlad2j9y0lptc
            unique
);

alter table users
    owner to postgres;

create table accounts
(
    id      bigint generated by default as identity
        constraint accounts_pkey
            primary key,
    balance bigint       not null,
    name    varchar(255) not null
        constraint uk_22fvt0prnafepjuqjhs2da68e
            unique,
    user_id bigint       not null
        constraint fknjuop33mo69pd79ctplkck40n
            references users
);

alter table accounts
    owner to postgres;

create table operations
(
    id         bigint generated by default as identity
        constraint operations_pkey
            primary key,
    amount     bigint    not null,
    timestamp  timestamp not null,
    account_id bigint    not null
        constraint fk3lft1gkkuyvhih1cst48xvm7q
            references accounts
);

alter table operations
    owner to postgres;

create table expense_categories_of_operations
(
    operation_id bigint not null
        constraint fkga0r49cyp4r67ggrohladrx8f
            references operations,
    category_id  bigint not null
        constraint fkrobocc8fs3jg7uclnl2dc53yf
            references expense_categories,
    constraint expense_categories_of_operations_pkey
        primary key (operation_id, category_id)
);

alter table expense_categories_of_operations
    owner to postgres;

create table income_categories_of_operations
(
    operation_id bigint not null
        constraint fkg9urrsmns6s46i4kxm20iwj8p
            references operations,
    category_id  bigint not null
        constraint fkjvyb5x213kieucm2oa77lfbxa
            references income_categories,
    constraint income_categories_of_operations_pkey
        primary key (operation_id, category_id)
);

alter table income_categories_of_operations
    owner to postgres;


